#!/usr/bin/env python

import glib
import gobject
import gst
import os.path
import thread
import sys
import time
import grooveshark
from urllib import quote_plus

__version__ = '0.1.0'

class Cli_Player(object):
    def __init__(self):
        self._gs_client = grooveshark.Client()
        self._player = gst.element_factory_make('playbin2', 'player')
        self._player.set_property('video-sink',
            gst.element_factory_make('fakesink', 'fakesink'))
        message_bus = self._player.get_bus()
        message_bus.add_signal_watch()
        message_bus.connect('message', self._on_message)

    def _on_message(self, bus, message):
        if message.type == gst.MESSAGE_EOS:
            self._player.set_state(gst.STATE_NULL)
            self.playing = False
        elif message.type == gst.MESSAGE_ERROR:
            self._player.set_state(gst.STATE_NULL)
            sys.stderr.write( 'Error: %s\nDebug: %s\n' % (err, debug))
            self.playing = False

    def start(self):
        self.playing = True
        self._gs_client
        self._player.set_property('uri', uri)
        self._player.set_state(gst.STATE_PLAYING)
        while self.playing:
            try:
                pos = self._player.query_position(gst.FORMAT_TIME, None)
            except gst.QueryError:
                pass
            else:
                sys.stdout.write('\r%04d' % (pos[0] // (10 ** 9)))
                sys.stdout.flush()
            time.sleep(0.2)
        time.sleep(1)
        main_loop.quit()

if __name__ == '__main__':
    thread.start_new_thread(Cli_Player().start, ())
    gobject.threads_init()
    main_loop = glib.MainLoop()
    try:
        main_loop.run()
    except KeyboardInterrupt:
        pass